version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - export GOOGLE_APPLICATION_CREDENTIALS="./src/environments/firebase.json"
      - echo $GOOGLE_APPLICATION_CREDENTIALS
      - cd ui
      - npm i
      - npm install -g firebase-tools

  build:
    commands:
      - npm run build:production

  post_build:
    commands:
      - firebase deploy --project color-recogniser-b18e3 --only hosting
