version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - cd ui
      - npm i

  build:
    commands:
      - aws s3 cp s3://color-recognizer-assets/firebase.json src/environments/
      - npm run build:production

  post_build:
    commands:
      - aws s3 sync ./dist/color-recogniser s3://colorrecognizer.io/ --acl 'public-read' --delete
