version: 0.2
env:
  variables:
    GOOGLE_APPLICATION_CREDENTIALS: "./ui/src/environments/firebase.json"
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - cd ui
      - npm i
      - npm install -g firebase-tools

  build:
    commands:
      - npm run build:production

  post_build:
    commands:
      - firebase deploy --project color-recogniser-b18e3 --only hosting
