version: 0.2
env:
  secrets-manager:
    GOOGLE_APPLICATION_CREDENTIALS: arn:aws:secretsmanager:ap-southeast-2:141714874243:secret:prod/ColorRecognizer/GOOGLE_APPLICATION_CREDENTIALS-JokIDW
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - cd ui
      - npm i
      - npm install -g firebase-tools

  build:
    commands:
      - npm run build:production

  post_build:
    commands:
      - firebase deploy --project color-recogniser-b18e3 --only hosting
