version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
  build:
    commands:
      - cd color-recognizer-serverless
      - sam validate
      - sam build
      - echo $StackName
      - sudo sam deploy --no-confirm-changeset --stack-name $StackName