version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
  build:
    commands:
      - cd color-recognizer-serverless
      - sam build
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset