version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
  build:
    commands:
      - cd color-recognizer-serverless
      - sam build
      - aws cloudformation delete-stack --stack-name $StackName
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset